version: '3.9'

services:
  bdres:
    image: postgres
    restart: always

    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: bdres
    ports:
      - "5432:5432"

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
      
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    user: "mongodb"  